
[advanced_recycler]
	#Format: item_id,output_id,amount
	inputs = ["thermal:gunpowder_block,reforgedutils:industrial_gunpowder,1", "ae2:singularity,reforgedutils:t5defence,64", "pneumaticcraft:unassembled_pcb,reforgedutils:pcb_meld,8", "mekanism:block_steel,reforgedutils:steel_rod,3", "reforgedutils:electric_piston,reforgedutils:small_motor,2", "minecraft:glowstone,minecraft:glowstone_dust,16", "reforgedutils:broken_graphics_card,reforgedutils:graphics_card,1", "minecraft:copper_ingot,reforgedutils:copper_wiring,1", "reforgedutils:robotic_arm,reforgedutils:electric_piston,4", "reforgedutils:electric_pump,reforgedutils:actuator,2", "minecraft:coal_block,reforgedutils:carbon_mesh,1", "reforgedutils:emitter,reforgedutils:fuse,16"]
	#Crafting speed for the advanced recycler (1200 = 1m, 20 = 1s)
	#Range: 1 ~ 1200
	crafting_speed = 100

[recycler]
	#Format: item_id,output_id,amount
	inputs = ["thermal:gunpowder_block,reforgedutils:industrial_gunpowder,1", "minecraft:copper_ingot,reforgedutils:copper_wiring,1", "reforgedutils:robotic_arm,reforgedutils:electric_piston,4", "reforgedutils:electric_pump,reforgedutils:actuator,2", "minecraft:coal_block,reforgedutils:carbon_mesh,1", "reforgedutils:emitter,reforgedutils:fuse,16"]
	#Crafting speed for the recycler (1200 = 1m, 20 = 1s)
	#Range: 1 ~ 1200
	crafting_speed = 100

[medkit]
	#Heal amount for the medkit
	#Range: 0.0 ~ 20.0
	heal_amount = 10.0
	#Cooldown duration for the medkit in ticks (6000 = 5m, 20 = 1s)
	#Range: 0 ~ 6000
	cooldown_duration = 200

[painkillers]
	#Heal amount for the painkillers
	#Range: 0.0 ~ 20.0
	heal_amount = 8.0
	#Cooldown duration for the painkillers in ticks (6000 = 5m, 20 = 1s)
	#Range: 0 ~ 6000
	cooldown_duration = 300

[full_blood_bag]
	#Heal amount for the full blood bag
	#Range: 0.0 ~ 20.0
	heal_amount = 10.0
	#Cooldown duration for the full blood bag in ticks (6000 = 5m, 20 = 1s)
	#Range: 0 ~ 6000
	cooldown_duration = 100

[energy_drink]
	#Format: effect_id,duration,amplifier
	effects = ["minecraft:speed,400,0", "minecraft:haste,400,1"]
	#Cooldown duration for the energy drink in ticks (6000 = 5m, 20 = 1s)
	#Range: 0 ~ 6000
	cooldown_duration = 600

[barrel]
	#Format: item_id,min-max quantity,chance (chance 0.1 ~ 1.0)
	barrel1_drops = ["reforgedutils:scrap_metal,2-5,1", "reforgedutils:screw,2-5,0.5", "reforgedutils:empty_can,2-5,0.5", "reforgedutils:small_battery,2-5,0.5", "reforgedutils:empty_canister,2-5,0.5", "reforgedutils:nail,2-5,1", "reforgedutils:electric_motor,2-5,1", "reforgedutils:actuator,2-5,0.5", "reforgedutils:automatic_gate,2-5,0.5", "reforgedutils:broken_filter,2-5,0.5", "reforgedutils:carbon_fibre,2-5,0.5", "reforgedutils:carbon_mesh,2-5,0.5", "reforgedutils:carbon_plate,2-5,0.5", "reforgedutils:copper_wiring,2-5,0.5", "reforgedutils:diode,2-5,0.5", "reforgedutils:rotor,2-5,0.5", "reforgedutils:small_conductor,2-5,0.5", "reforgedutils:small_motor,2-5,0.5", "reforgedutils:solenoid,2-5,0.5"]
	#Format: item_id,min-max quantity,chance (chance 0.1 ~ 1.0)
	barrel2_drops = ["reforgedutils:battery,2-5,1", "reforgedutils:air_filter,2-5,0.5", "reforgedutils:emitter,2-5,0.5", "reforgedutils:redstone_wires,2-5,0.5", "reforgedutils:fuel_cell,2-5,1", "reforgedutils:broken_graphics_card,2-5,1", "reforgedutils:control_circuit,2-5,0.5", "reforgedutils:cpu,2-5,1", "reforgedutils:electric_piston,2-5,1", "reforgedutils:electric_pump,2-5,1", "reforgedutils:fuse,2-5,0.5", "reforgedutils:hdd,2-5,1", "reforgedutils:ram,2-5,1", "reforgedutils:sulfuric_acid,2-5,0.5", "reforgedutils:robotic_arm,2-5,1", "reforgedutils:ssd,2-5,1"]
	#Max number of different items and commands that a barrel will drop (range 1 ~ 10)
	#Range: 1 ~ 10
	max_drops = 3
	#Respawn time for barrels in ticks  (72000 = 60m, 20 = 1s)
	#Range: 20 ~ 72000
	respawn_ticks = 12000

